return {
  -- Nothing to see here
  -- "yetone/avante.nvim",
  -- build = "make",
  -- event = "VeryLazy",
  -- version = false, -- Never set this value to "*"! Never!
  -- ---@module 'avante'
  -- ---@type avante.Config
  -- opts = {
  --   mode = "legacy", 
  --   provider = "claude",
  --   providers = {
  --     claude = {
  --       auth_type = "max",
  --       model = "claude-sonnet-4-6",
  --     },
  --   },
  -- },
  -- dependencies = {
  --   "nvim-lua/plenary.nvim",
  --   "MunifTanjim/nui.nvim",
  --   --- The below dependencies are optional,
  --   "stevearc/dressing.nvim", -- for input provider dressing
  --   {
  --     -- Make sure to set this up properly if you have lazy=true
  --     'MeanderingProgrammer/render-markdown.nvim',
  --     opts = {
  --       file_types = { "Avante" },
  --     },
  --     ft = { "Avante" },
  --   },
  -- },
}
